In [1]:
!pip install keras

import math
import os
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

from sklearn.model_selection import train_test_split


distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


## Load Cleaned Data

In [2]:
data = pd.read_csv("cleaned_data.csv", sep=",")

columns = data.columns

print(data.columns)

Index(['Unnamed: 0', 'p1/head:tx', 'p1/head:ty', 'p1/head:tz', 'p1/hand_l:tx',
       'p1/hand_l:ty', 'p1/hand_l:tz', 'p1/hand_r:tx', 'p1/hand_r:ty',
       'p1/hand_r:tz', 'p1/foot_l:tx', 'p1/foot_l:ty', 'p1/foot_l:tz',
       'p1/foot_r:tx', 'p1/foot_r:ty', 'p1/foot_r:tz', 'p1/hip_l:tx',
       'p1/hip_l:ty', 'p1/hip_l:tz', 'p1/hip_r:tx', 'p1/hip_r:ty',
       'p1/hip_r:tz', 'p1/shoulder_l:tx', 'p1/shoulder_l:ty',
       'p1/shoulder_l:tz', 'p1/shoulder_r:tx', 'p1/shoulder_r:ty',
       'p1/shoulder_r:tz', 'p1/shoulder_c:tx', 'p1/shoulder_c:ty',
       'p1/shoulder_c:tz', 'p1/knee_l:tx', 'p1/knee_l:ty', 'p1/knee_l:tz',
       'p1/knee_r:tx', 'p1/knee_r:ty', 'p1/knee_r:tz', 'p1/elbow_l:tx',
       'p1/elbow_l:ty', 'p1/elbow_l:tz', 'p1/elbow_r:tx', 'p1/elbow_r:ty',
       'p1/elbow_r:tz', 'p1/head:dx', 'p1/head:dy', 'p1/head:dz',
       'p1/hand_l:dx', 'p1/hand_l:dy', 'p1/hand_l:dz', 'p1/hand_r:dx',
       'p1/hand_r:dy', 'p1/hand_r:dz', 'p1/foot_l:dx', 'p1/foot_l:dy',
       'p1/foot_

In [42]:
timesteps = 200
input_dim = 42

prev_user = None
train_data = []
xs = []

for row in data.itertuples():
    user = row.user
    classification = row.classification
    
    if user != prev_user:
        if prev_user == None:
            prev_user = user
            next
        
        print(user)
        prev_user = user
        train_data.append([xs, classification])
        xs = []


    x = row[-44:-2]
    xs.extend([x])




train_data = np.array(train_data)

# print(train_data[3])

dftrain, dftest = train_test_split(train_data, test_size=0.2)
x_train = [np.array(col[0]) for col in dftrain]
y_train = [col[1] for col in dftrain]
x_test = [np.array(col[0]) for col in dftest]
y_test = [col[1] for col in dftest]


print(len(dftrain))
print(len(dftest))

print(y_train[0])
print(x_train[0])

# print(y_train)

dancing_alden.tsv
dancing_asha.tsv
dancing_dan.tsv
dancing_jason.tsv
dancing_mai.tsv
dancing_max.tsv
dancing_me.tsv
dancing_nico.tsv
dancing_nicolas.tsv
dancing_roland.tsv
dancing_will.tsv
notdancing_alden.tsv
notdancing_asha.tsv
notdancing_dan.tsv
notdancing_jason.tsv
notdancing_mai.tsv
notdancing_max.tsv
notdancing_me.tsv
notdancing_nico.tsv
notdancing_nicolas.tsv
notdancing_roland.tsv
notdancing_shreiya.tsv
notdancing_will.tsv
18
5
0.0
[[ 2.4009160e-02  4.0241600e-03  2.6284400e-02 ...  2.3928320e-02
   7.6115480e-03  1.6121600e-02]
 [ 4.3428700e-02  1.1206000e-03  1.8739200e-02 ...  9.4422600e-03
   6.0066714e-02 -1.1294600e-02]
 [ 1.6822360e-02  1.3038920e-02  3.4292000e-03 ...  1.2720400e-03
   5.5485612e-02 -1.4593200e-02]
 ...
 [ 4.8120000e-04 -6.5086000e-04 -2.4240000e-04 ... -3.1134000e-04
  -1.5761200e-04  7.7780000e-04]
 [ 8.5248000e-04 -1.2180000e-03 -6.6040000e-04 ...  5.2044000e-04
   6.8520000e-06  1.0500000e-03]
 [ 2.1564400e-03 -3.2135800e-03 -1.9414000e-03 ...  1.614

## Prepare Data

In [54]:
diff_columns = [col for col in columns if re.match(r".*d.$", col)]
diff_columns.extend(['classification'])

dftrain = data[diff_columns]

dftrain, dftest = train_test_split(data[diff_columns], test_size=0.2)

# Training data
x_train = dftrain[diff_columns]
y_train = dftrain['classification']

# Test data
x_test = dftest[diff_columns]
y_test = dftest['classification']

print(x_train)
print(y_train)

print(diff_columns)

      p1/head:dx  p1/head:dy  p1/head:dz  p1/hand_l:dx  p1/hand_l:dy  \
703     0.003441   -0.010583   -0.028262      0.051805     -0.006752   
1783   -0.022781   -0.002775    0.008987     -0.014053     -0.005014   
1370    0.023194    0.008591   -0.001308      0.034563      0.039009   
3431    0.028514    0.000297    0.002326      0.025015      0.005417   
1205    0.071625   -0.015186   -0.034286      0.037128     -0.000814   
433    -0.002718   -0.003186   -0.008066     -0.004913     -0.027240   
797     0.010013   -0.017901   -0.016801      0.026054     -0.078083   
3118    0.011165    0.004047   -0.003732     -0.037443      0.028383   
4231    0.029788   -0.008503   -0.006106      0.010882     -0.000063   
2253   -0.004144   -0.003619    0.000968     -0.020249      0.025333   
1875   -0.028627   -0.025452    0.058227      0.133389     -0.198524   
76      0.015046   -0.007204    0.052710     -0.110130     -0.034202   
2617   -0.016449    0.000508    0.016336     -0.029788     -0.01

In [44]:
# from example

fakex_train = np.random.random((1000, timesteps, data_dim))
fakey_train = np.random.random((1000, num_classes))

print(timesteps)
print(data_dim)
print(type(fakex_train))
print(type(np.ndarray(x_train)))
print(fakex_train[2])
print(x_train[2])

200
42
<class 'numpy.ndarray'>


TypeError: only integer scalar arrays can be converted to a scalar index

## Train

In [40]:
data_dim = 42
timesteps = 200
num_classes = 2

# expected input data shape: (batch_size, timesteps, data_dim)
model = Sequential()
model.add(LSTM(32, return_sequences=True,
               input_shape=(timesteps, data_dim)))  # returns a sequence of vectors of dimension 42
model.add(LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32))  # return a single vector of dimension 32
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])


model.fit(x_train, y_train,
          batch_size=1, epochs=5)


# model.predict(x_test)

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 18 arrays: [array([[ 0.0234914 ,  0.0036742 ,  0.0066016 , ...,  0.010187  ,
         0.0057344 , -0.0140008 ],
       [ 0.02832682,  0.00335702,  0.0022358 , ...,  0.02072374,
         0.00444246, -0.0116132 ],...

In [30]:
print(x_train[0])

[[0.34158772 0.76788325 0.55376324 ... 0.73262943 0.79545617 0.43927229]
 [0.07274669 0.31278729 0.01525534 ... 0.66751965 0.43657974 0.46063277]
 [0.73012253 0.044247   0.81713062 ... 0.2552919  0.54264535 0.33944658]
 ...
 [0.36313183 0.17641259 0.47437952 ... 0.45834552 0.02398759 0.41426352]
 [0.15092495 0.18552565 0.136178   ... 0.52719038 0.6250653  0.55409114]
 [0.45209888 0.51370893 0.26052288 ... 0.06023967 0.30422309 0.20964024]]


In [15]:
import pandas as pd
x_train = pd.read_csv('training_data.csv', sep=',',header=1)
x_train.values

x_train.tail()


50  1.3046719999999998  -0.38843049999999996  3.393734  0.8746868  \
22994  1045            0.805225             -0.064882  2.703505   0.529117   
22995  1046            0.807749             -0.072318  2.692815   0.536634   
22996  1047            0.807749             -0.072318  2.692815   0.536634   
22997  1048            0.808892             -0.081096  2.680727   0.543384   
22998  1049            0.808892             -0.081096  2.680727   0.543384   

       -0.6795787  3.3568839999999995  0.8905584999999999  -0.6281642  \
22994   -0.748536            2.817768            0.766553   -0.729576   
22995   -0.751952            2.808611            0.769255   -0.738360   
22996   -0.751952            2.808611            0.769255   -0.738360   
22997   -0.763010            2.796647            0.771182   -0.748278   
22998   -0.763010            2.796647            0.771182   -0.748278   

       3.383114     ...       -1.462777  3.551411  1.055417  \
22994  2.835117     ...       -1.123607  3.249849  0.427156   
22995  2.822912     ...       -1.132008  3.242096  0.423794   
22996  2.822912     ...       -1.132008  3.242096  0.423794   
22997  2.809686     ...       -1.137862  3.231271  0.422788   
22998  2.809686     ...       -1.137862  3.231271  0.422788   

       -0.7448916999999999  3.120533  1.0443719999999999  -0.6931599  \
22994            -0.474788  2.765285            0.902814   -0.500578   
22995            -0.483205  2.754180            0.904506   -0.510160   
22996            -0.483205  2.754180            0.904506   -0.510160   
22997            -0.496354  2.734586            0.905004   -0.519088   
22998            -0.496354  2.734586            0.905004   -0.519088   

       3.1474599999999997  alden      dancing  
22994            2.897322   will  not dancing  
22995            2.882418   will  not dancing  
22996            2.882418   will  not dancing  
22997            2.868947   will  not dancing  
22998            2.868947   will  not dancing  

[5 rows x 45 columns]

In [21]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras.layers import LSTM

max_features = 1024

model = Sequential()
model.add(Embedding(max_features, output_dim=256))
model.add(LSTM(128))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=16, epochs=10)
score = model.evaluate(x_test, y_test, batch_size=16)

ValueError: Error when checking target: expected dense_8 to have shape (1,) but got array with shape (10,)